name: Build 11ty

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
      - 'release-test'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
      deploy:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - uses: actions/checkout@master

          - name: Setup node.js
            uses: actions/setup-node@latest
            with:
              node-version: latest

          - name: Install and build
            run: |
              npm install
              npm run build

          - name: Deploy
            uses: peaceiris/actions-gh-pages@latest
            with:
              publish_dir: site
              publish_branch: production
              github_token: ${{ secrets.GITHUB_TOKEN }}
